name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/containerd-shim-ironbox-v1
          generate_release_notes: true
